apiVersion: 1

datasources:
  - name: Analytics API
    type: grafana-simple-json-datasource
    access: proxy
    url: http://analytics-api:3008/api
    isDefault: true
    editable: true
    
  - name: Analytics Database
    type: postgres
    access: proxy
    url: analytics-db:5432
    database: analytics
    user: analytics
    secureJsonData:
      password: analytics_password
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: true
    
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://analytics-prometheus:9090
    editable: true